apiVersion: v1
kind: Service
metadata:
  name: daydaystudy-service
  namespace: daydaystudy-service
  labels:
    app: daydaystudy-service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: daydaystudy-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daydaystudy-service
  namespace: devops-weiming-first
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daydaystudy-service
  template:
    metadata:
      labels:
        app: daydaystudy-service
        version: v1
    spec:
      containers:
        - name: daydaystudy-app
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/daydaystudy:SNAPSHOT-$BUILD_NUMBER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
